# Generated by Django 3.1.7 on 2021-12-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
