# Generated by Django 3.1.7 on 2021-12-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pit_stats_hide',
            field=models.BooleanField(default=False),
        ),
    ]
