# Generated by Django 3.1.7 on 2021-12-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_pit_stats_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pit_stats_hide',
        ),
    ]
