# Generated by Django 3.1.7 on 2021-12-03 00:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 0, 58, 8, 806735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userId',
            field=models.IntegerField(default=6002782),
        ),
    ]
