# Generated by Django 3.1.7 on 2022-01-11 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 16, 40, 1, 491845, tzinfo=utc)),
        ),
    ]
