# Generated by Django 3.1.7 on 2021-12-03 01:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211203_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 1, 7, 38, 984843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userId',
            field=models.IntegerField(default=4521269),
        ),
    ]
