# Generated by Django 3.1.7 on 2022-01-12 00:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220112_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 0, 24, 48, 621986, tzinfo=utc)),
        ),
    ]
