# Generated by Django 3.1.7 on 2021-12-03 01:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211203_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userId',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 1, 11, 26, 149846, tzinfo=utc)),
        ),
    ]
