# Generated by Django 3.1.7 on 2021-12-05 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211203_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 16, 15, 8, 642672, tzinfo=utc)),
        ),
    ]
