# Generated by Django 3.1.7 on 2022-01-12 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220112_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='viewPitResubmit',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 16, 47, 19, 163381, tzinfo=utc)),
        ),
    ]
