# Generated by Django 3.1.7 on 2021-12-05 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211205_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 21, 12, 13, 514957, tzinfo=utc)),
        ),
    ]
