# Generated by Django 3.1.7 on 2021-12-11 21:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211205_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userId',
        ),
        migrations.AddField(
            model_name='profile',
            name='dm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 21, 28, 30, 36820, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
