# Generated by Django 3.1.7 on 2021-12-03 00:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_remove_team_pit_stats_hide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Pit_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(default=datetime.datetime(2021, 12, 3, 0, 49, 2, 798907, tzinfo=utc))),
                ('team_num', models.IntegerField(null=True)),
                ('competition', models.CharField(max_length=100, null=True)),
                ('scouted_team_num', models.CharField(max_length=100, null=True)),
                ('robot_weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('robot_frame_length', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('robot_frame_width', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('robot_drivetrain_type', models.CharField(max_length=100, null=True)),
                ('robot_vision_type', models.CharField(max_length=100, null=True)),
                ('robot_vision_implement', models.CharField(max_length=100, null=True)),
                ('robot_goal', models.CharField(max_length=100, null=True)),
                ('robot_autonomous', models.CharField(max_length=100, null=True)),
                ('robot_highlow', models.CharField(max_length=100, null=True)),
                ('robot_climb', models.CharField(max_length=100, null=True)),
                ('robot_buddy_climb', models.CharField(max_length=100, null=True)),
                ('robot_control_panel_rot', models.CharField(max_length=100, null=True)),
                ('robot_control_panel_pos', models.CharField(max_length=100, null=True)),
                ('stat_id', models.CharField(max_length=15, null=True)),
                ('notes', models.TextField(max_length=100, null=True)),
                ('is_incorrect', models.BooleanField()),
                ('scout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_num', models.IntegerField(null=True)),
                ('competition', models.CharField(max_length=100, null=True)),
                ('match_number', models.IntegerField(null=True)),
                ('match_type', models.CharField(max_length=100, null=True)),
                ('scouted_team_num', models.IntegerField(null=True)),
                ('scouted_team_code', models.CharField(max_length=100, null=True)),
                ('initiation_line', models.CharField(max_length=100, null=True)),
                ('auto_low_goal_scored', models.IntegerField(null=True)),
                ('auto_outer_goal_scored', models.IntegerField(null=True)),
                ('auto_inner_goal_scored', models.IntegerField(null=True)),
                ('low_goal_scored', models.IntegerField(null=True)),
                ('outer_goal_scored', models.IntegerField(null=True)),
                ('inner_goal_scored', models.IntegerField(null=True)),
                ('control_panel_rot', models.CharField(max_length=3, null=True)),
                ('control_panel_pos', models.CharField(max_length=3, null=True)),
                ('robot_climb', models.CharField(max_length=3, null=True)),
                ('robot_generator', models.CharField(max_length=3, null=True)),
                ('defense_played', models.CharField(max_length=3, null=True)),
                ('defense_percentage', models.IntegerField(null=True)),
                ('robot_climb_help', models.CharField(max_length=100, null=True)),
                ('penalties', models.CharField(max_length=100, null=True)),
                ('notes', models.TextField(max_length=100, null=True)),
                ('match_id', models.CharField(max_length=10, null=True)),
                ('score', models.IntegerField(null=True)),
                ('scout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scouter', to=settings.AUTH_USER_MODEL)),
                ('stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.game_stats')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=100)),
                ('match_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stats.match')),
            ],
        ),
    ]
