# Generated by Django 3.1.7 on 2022-01-10 21:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Pit_stats',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_entered', models.DateTimeField(default=datetime.datetime(2022, 1, 10, 21, 32, 50, 694431, tzinfo=utc))),
                ('team_num', models.IntegerField(null=True)),
                ('competition', models.CharField(max_length=100, null=True)),
                ('scouting_team', models.CharField(max_length=100, null=True)),
                ('robot_weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('robot_frame_length', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('robot_frame_width', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('robot_drivetrain_type', models.CharField(max_length=100, null=True)),
                ('robot_vision_type', models.CharField(max_length=100, null=True)),
                ('robot_vision_implement', models.CharField(max_length=100, null=True)),
                ('robot_goal_height', models.CharField(max_length=100, null=True)),
                ('robot_autonomous', models.CharField(max_length=100, null=True)),
                ('robot_climb', models.CharField(max_length=100, null=True)),
                ('customOne', models.CharField(blank=True, max_length=100, null=True)),
                ('customTwo', models.CharField(blank=True, max_length=100, null=True)),
                ('customThree', models.CharField(blank=True, max_length=100, null=True)),
                ('answerOne', models.CharField(blank=True, max_length=100, null=True)),
                ('answerTwo', models.CharField(blank=True, max_length=100, null=True)),
                ('answerThree', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(max_length=100, null=True)),
                ('is_incorrect', models.BooleanField()),
                ('incorrect_selection', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('scout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_num', models.IntegerField(null=True)),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('left_tarmac', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_lower', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_upper', models.CharField(blank=True, max_length=100, null=True)),
                ('lower', models.CharField(blank=True, max_length=100, null=True)),
                ('upper', models.CharField(blank=True, max_length=100, null=True)),
                ('opposite_color', models.CharField(blank=True, max_length=100, null=True)),
                ('robot_climb', models.CharField(blank=True, max_length=100, null=True)),
                ('defense_percentage', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('scout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scouter', to=settings.AUTH_USER_MODEL)),
                ('stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.game_stats')),
            ],
        ),
    ]
