# Generated by Django 2.2.14 on 2022-02-28 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('comp', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Pit_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_id', models.CharField(max_length=15, null=True)),
                ('team_num', models.PositiveIntegerField()),
                ('competition', models.CharField(max_length=100, null=True)),
                ('date_entered', models.DateTimeField(default=datetime.datetime(2022, 2, 28, 22, 0, 19, 544525))),
                ('robot_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('robot_frame_length', models.PositiveIntegerField(blank=True, null=True)),
                ('robot_frame_width', models.PositiveIntegerField(blank=True, null=True)),
                ('robot_drivetrain_type', models.CharField(blank=True, max_length=100, null=True)),
                ('robot_vision_type', models.CharField(blank=True, max_length=100, null=True)),
                ('robot_vision_implement', models.CharField(blank=True, max_length=100, null=True)),
                ('robot_goal_height', models.CharField(blank=True, max_length=100, null=True)),
                ('robot_autonomous', models.CharField(blank=True, max_length=100, null=True)),
                ('robot_climb', models.CharField(blank=True, max_length=100, null=True)),
                ('customOne', models.CharField(blank=True, max_length=100, null=True)),
                ('customTwo', models.CharField(blank=True, max_length=100, null=True)),
                ('customThree', models.CharField(blank=True, max_length=100, null=True)),
                ('answerOne', models.CharField(blank=True, max_length=100, null=True)),
                ('answerTwo', models.CharField(blank=True, max_length=100, null=True)),
                ('answerThree', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, max_length=100, null=True)),
                ('is_incorrect', models.BooleanField(default=False)),
                ('incorrect_selection', models.CharField(blank=True, max_length=100, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('scout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_num', models.IntegerField(null=True)),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('left_tarmac', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_lower', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_upper', models.CharField(blank=True, max_length=100, null=True)),
                ('lower', models.CharField(blank=True, max_length=100, null=True)),
                ('upper', models.CharField(blank=True, max_length=100, null=True)),
                ('opposite_color', models.CharField(blank=True, max_length=100, null=True)),
                ('robot_climb', models.CharField(blank=True, max_length=100, null=True)),
                ('updatingEntry', models.BooleanField(default=False)),
                ('defense_percentage', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('scout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scouter', to=settings.AUTH_USER_MODEL)),
                ('stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Game_stats')),
            ],
        ),
    ]
