# Generated by Django 3.1.7 on 2022-01-11 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pit_stats',
            name='incorrect_selection',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='robot_goal_height',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='scouting_team',
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_buddy_climb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_control_panel_pos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_control_panel_rot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_goal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_highlow',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='scouted_team_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 16, 38, 1, 639913, tzinfo=utc)),
        ),
    ]
