# Generated by Django 3.1.7 on 2021-12-03 01:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20211203_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 1, 16, 32, 322021, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
