# Generated by Django 3.1.7 on 2022-01-11 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20220111_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 16, 39, 28, 458856, tzinfo=utc)),
        ),
    ]
