# Generated by Django 3.1.7 on 2021-12-05 21:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20211203_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pit_stats',
            name='is_hidden',
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 21, 12, 13, 517767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=100)),
                ('match_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stats.match')),
            ],
        ),
    ]
