# Generated by Django 3.1.7 on 2021-12-05 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20211205_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 21, 14, 5, 886602, tzinfo=utc)),
        ),
    ]
