# Generated by Django 3.1.7 on 2021-12-11 21:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20211205_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='stat_id',
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 21, 28, 30, 44314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='is_incorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
