# Generated by Django 3.1.7 on 2022-01-11 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20220111_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 16, 40, 9, 949632, tzinfo=utc)),
        ),
    ]
