# Generated by Django 3.1.7 on 2021-12-16 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20211211_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit_stats',
            name='answerOne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='answerThree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='answerTwo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='customOne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='customThree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='customTwo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 16, 39, 27, 436017, tzinfo=utc)),
        ),
    ]
