# Generated by Django 3.1.7 on 2021-12-19 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20211216_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 17, 45, 38, 32623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='is_incorrect',
            field=models.BooleanField(),
        ),
    ]
