# Generated by Django 3.1.7 on 2022-01-11 22:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20220111_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 22, 43, 15, 631341, tzinfo=utc)),
        ),
    ]
