# Generated by Django 3.1.7 on 2022-01-03 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20211219_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit_stats',
            name='incorrect_selection',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 20, 56, 50, 373389, tzinfo=utc)),
        ),
    ]
