# Generated by Django 2.2.14 on 2022-03-01 16:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0009_auto_20220301_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 16, 17, 22, 234625)),
        ),
        migrations.CreateModel(
            name='Archived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_num', models.IntegerField(null=True)),
                ('competition', models.CharField(max_length=100, null=True)),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('left_tarmac', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_lower', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_upper', models.CharField(blank=True, max_length=100, null=True)),
                ('lower', models.CharField(blank=True, max_length=100, null=True)),
                ('upper', models.CharField(blank=True, max_length=100, null=True)),
                ('opposite_color', models.CharField(blank=True, max_length=100, null=True)),
                ('robot_climb', models.CharField(blank=True, max_length=100, null=True)),
                ('updatingEntry', models.BooleanField(default=False)),
                ('defense_percentage', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('scout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scout', to=settings.AUTH_USER_MODEL)),
                ('stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Game_stats')),
            ],
        ),
    ]
