# Generated by Django 3.1.7 on 2022-01-11 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20220111_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pit_stats',
            name='scouting_team',
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 22, 45, 0, 41413, tzinfo=utc)),
        ),
    ]
