# Generated by Django 3.1.7 on 2022-01-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20220111_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pit_stats',
            name='answerOne',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='answerThree',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='answerTwo',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='customOne',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='customThree',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='customTwo',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='date_entered',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='robot_autonomous',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='robot_climb',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='robot_drivetrain_type',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='robot_frame_width',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='robot_goal_height',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='robot_vision_implement',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='robot_vision_type',
        ),
        migrations.RemoveField(
            model_name='pit_stats',
            name='scout',
        ),
    ]
