# Generated by Django 3.1.7 on 2022-01-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20220111_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit_stats',
            name='robot_autonomous',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_climb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_drivetrain_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_frame_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_goal_height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_vision_implement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='robot_vision_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='team_num',
            field=models.IntegerField(default=810),
        ),
    ]
