# Generated by Django 2.2.14 on 2022-03-01 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20220301_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_stats_archived',
            name='team',
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 16, 23, 48, 732511)),
        ),
        migrations.DeleteModel(
            name='Archived',
        ),
        migrations.DeleteModel(
            name='Game_stats_archived',
        ),
    ]
