# Generated by Django 3.1.7 on 2022-01-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_pit_stats_robot_goal_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit_stats',
            name='robot_vision_implement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
