# Generated by Django 3.1.7 on 2022-01-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_auto_20220112_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pit_stats',
            name='robot_vision_type',
        ),
    ]
