# Generated by Django 3.1.7 on 2022-01-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_pit_stats_robot_vision_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit_stats',
            name='robot_climb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
