# Generated by Django 3.1.7 on 2022-01-12 00:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220112_0018'),
        ('stats', '0022_remove_pit_stats_robot_buddy_climb'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit_stats',
            name='competition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 0, 18, 25, 481079, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='pit_stats',
            name='scout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
