# Generated by Django 3.1.7 on 2022-01-12 00:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_auto_20220112_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pit_stats',
            name='scout',
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 0, 19, 24, 608917, tzinfo=utc)),
        ),
    ]
