# Generated by Django 3.1.7 on 2022-01-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_auto_20220112_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pit_stats',
            name='date_entered',
        ),
    ]
