# Generated by Django 3.1.7 on 2022-01-12 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0026_pit_stats_scout'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 0, 25, 39, 43293, tzinfo=utc)),
        ),
    ]
