# Generated by Django 3.1.7 on 2022-01-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_pit_stats_date_entered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pit_stats',
            name='date_entered',
        ),
    ]
