# Generated by Django 3.1.7 on 2022-01-12 00:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0028_remove_pit_stats_date_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 0, 28, 22, 483248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='scout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
