# Generated by Django 3.1.7 on 2022-01-12 00:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220112_0028'),
        ('stats', '0029_auto_20220112_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 0, 28, 45, 795950, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='scout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
