# Generated by Django 3.1.7 on 2022-01-12 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0031_auto_20220112_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 16, 34, 12, 600285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='robot_frame_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='robot_frame_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='robot_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='team_num',
            field=models.PositiveIntegerField(default=810),
        ),
    ]
