# Generated by Django 3.1.7 on 2022-01-12 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0033_auto_20220112_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 19, 23, 40, 900124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
