# Generated by Django 3.1.7 on 2022-01-12 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0039_auto_20220112_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 20, 27, 39, 570509, tzinfo=utc)),
        ),
    ]
