# Generated by Django 3.1.7 on 2022-01-12 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0041_auto_20220112_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit_stats',
            name='stat_id',
            field=models.CharField(default=3, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pit_stats',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 22, 5, 31, 982761, tzinfo=utc)),
        ),
    ]
